default_install_hook_types: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        types: [python]
        language: system
        stages: [pre-commit]

      - id: flake8
        name: flake8
        entry: poetry run flake8
        types: [python]
        language: system
        stages: [pre-commit]

      - id: isort
        name: isort
        entry: poetry run isort
        types: [python]
        language: system
        stages: [pre-commit]

      - id: mypy
        name: mypy
        entry: poetry run mypy
        types: [python]
        language: system
        stages: [pre-commit]
        exclude: ^alembic/

      - id: black_all_files
        name: black_all_files
        entry: poetry run black .
        pass_filenames: false
        language: system
        stages: [pre-push]

      - id: flake8_all_files
        name: flake8_all_files
        entry: poetry run flake8 .
        pass_filenames: false
        language: system
        stages: [pre-push]

      - id: isort_all_files
        name: isort_all_files
        entry: poetry run isort .
        pass_filenames: false
        language: system
        stages: [pre-push]

      - id: mypy_all_files
        name: mypy_all_files
        entry: poetry run mypy .
        pass_filenames: false
        language: system
        stages: [pre-push]

      - id: unit-tests
        name: Unit tests
        entry: poetry run pytest src/tests/
        pass_filenames: false
        language: system
        stages: [pre-push]